language: node_js
node_js:
  - "v12.16.1"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
  - nyc mocha ./index.js --exit
  - nyc report --reporter=text-lcov > coverage.lcov && codecov -t 6d18023f-e108-406d-bfba-173dd3dfa0ab
